void setEffects(){ //name, value mod when applied to self
  effectsValue.put("speed", 0.4); 
  effectsValue.put("slowness", -0.4); 
  effectsValue.put("haste", 0.7); 
  effectsValue.put("mining fatigue", -0.7); 
  effectsValue.put("strength", 1.0);
  effectsValue.put("instant health", 10.0);
  effectsValue.put("instant damage", -10.0);
  effectsValue.put("fire", -1.3);
  effectsValue.put("jump boost", 0.4);
  effectsValue.put("nausia", -1.0);
  effectsValue.put("bad luck", -0.7);
  effectsValue.put("slow falling", 1.0);
  effectsValue.put("dolphin's grace", 0.4);
  effectsValue.put("luck", 0.7);
  effectsValue.put("regeneration", 1.3);
  effectsValue.put("poison", -1.0);
  effectsValue.put("resistance", 1.0);
  effectsValue.put("fire resistance", 1.3);
  effectsValue.put("water breathing", 1.0);
  effectsValue.put("invisibility", 0.4);
  effectsValue.put("blindness", -1.0);
  effectsValue.put("night vision", 1.0);
  effectsValue.put("hunger", -0.2);
  effectsValue.put("weakness", -1.0);
  effectsValue.put("wither", -1.6);
  effectsValue.put("health boost", 1.6);
  effectsValue.put("absorbsion", 1.0);
  effectsValue.put("saturation", 1.0);
  effectsValue.put("levitation", 1.0);
  
  effects[0] = "speed";
  effects[1] = "slowness";
  effects[2] = "haste";
  effects[3] = "mining fatigue";
  effects[4] = "strength";
  effects[5] = "instant health";
  effects[6] = "instant damage";
  effects[7] = "fire";
  effects[8] = "jump boost";
  effects[9] = "nausia";
  effects[10] = "bad luck";
  effects[11] = "slow falling";
  effects[12] = "dolphin's grace";
  effects[13] = "luck";
  effects[14] = "regeneration";
  effects[15] = "poison";
  effects[16] = "resistance";
  effects[17] = "fire resistance";
  effects[18] = "water breathing";
  effects[19] = "invisibility";
  effects[20] = "blindness";
  effects[21] = "night vision";
  effects[22] = "hunger";
  effects[23] = "weakness";
  effects[24] = "wither";
  effects[25] = "health boost";
  effects[26] = "absorbsion";
  effects[27] = "saturation";
  effects[28] = "levitation";
}  
